const mongoose = require('mongoose');

const projectSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    title: {
      type: String,
      required: [true, 'Please provide a project title'],
      trim: true,
    },
    description: {
      type: String,
      default: '',
      trim: true,
    },
    techStack: {
      type: [String],
      default: [],
    },
    architectureType: {
      type: String,
      enum: ['Full-stack MERN', 'Microservices', 'Serverless', 'REST API', 'Custom'],
      default: 'Full-stack MERN',
    },
    prompt: {
      type: String,
      default: '',
    },
    blueprintContent: {
      type: String,
      default: '',
    },
    status: {
      type: String,
      enum: ['draft', 'generating', 'completed', 'failed'],
      default: 'draft',
    },
    // Structured blueprint fields generated by AI
    systemArchitecture: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    modules: {
      type: mongoose.Schema.Types.Mixed,
      default: [],
    },
    databaseDesign: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
    apiDesign: {
      type: mongoose.Schema.Types.Mixed,
      default: [],
    },
    roadmap: {
      type: mongoose.Schema.Types.Mixed,
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

module.exports = mongoose.model('Project', projectSchema);
